# Generated by Django 5.0 on 2025-12-30 07:15

import django.contrib.postgres.search
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('what_it_does', models.TextField()),
                ('inputs_dependencies', models.TextField(blank=True, default='')),
                ('desired_outputs', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=10)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='', max_length=15)),
                ('estimated_time', models.CharField(blank=True, default='', max_length=50)),
                ('github_url', models.URLField(blank=True, default='', max_length=500)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project Tag',
                'verbose_name_plural': 'Project Tags',
                'db_table': 'project_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTagMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project Tag Map',
                'verbose_name_plural': 'Project Tag Maps',
                'db_table': 'project_tag_maps',
            },
        ),
    ]
