# Generated by Django 5.0 on 2025-12-30 07:15

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='host_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecttagmap',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_maps', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projecttagmap',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_maps', to='projects.projecttag'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['host_user', 'status'], name='project_host_status_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', '-created_at'], name='project_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='project_search_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttagmap',
            index=models.Index(fields=['project'], name='tagmap_project_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttagmap',
            index=models.Index(fields=['tag'], name='tagmap_tag_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projecttagmap',
            unique_together={('project', 'tag')},
        ),
    ]
