# Generated by Django 5.0 on 2026-01-04 00:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_initial"),
    ]

    operations = []
