# Generated by Django 5.0 on 2026-01-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_projectnote_projectresource"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="usage_type",
            field=models.CharField(
                choices=[("commercial", "Commercial"), ("practice", "Practice")],
                db_index=True,
                default="practice",
                max_length=15,
            ),
        ),
    ]
