# Generated by Django 5.0 on 2026-01-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_project_usage_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_ai_generated",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indicates if this project was generated by AI as inspiration",
            ),
        ),
    ]
