# Generated by Django 5.0 on 2025-12-30 11:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('soft_delete_project', 'Soft Delete Project'), ('soft_delete_contribution', 'Soft Delete Contribution'), ('ban_user', 'Ban User'), ('unban_user', 'Unban User'), ('reverse_credit', 'Reverse Credit')], db_index=True, max_length=50)),
                ('reason', models.TextField(max_length=1000)),
                ('moderator_email', models.EmailField(max_length=254)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.UUIDField(db_index=True)),
                ('target_description', models.TextField(max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moderation Log',
                'verbose_name_plural': 'Moderation Logs',
                'db_table': 'moderation_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='modlog_action_created_idx'), models.Index(fields=['target_type', 'target_id'], name='modlog_target_idx'), models.Index(fields=['moderator', '-created_at'], name='modlog_moderator_idx')],
            },
        ),
    ]
