# Generated by Django 5.0 on 2025-12-30 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contributions', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='contributor_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contribution',
            name='decided_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contribution',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['project', 'status', '-created_at'], name='contrib_project_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['contributor_user', 'status', '-created_at'], name='contrib_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['decided_by_user'], name='contrib_decided_by_idx'),
        ),
        migrations.AddConstraint(
            model_name='contribution',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'pending'), ('decided_by_user__isnull', True), ('decided_at__isnull', True)), models.Q(('status__in', ['accepted', 'declined']), ('decided_by_user__isnull', False), ('decided_at__isnull', False)), _connector='OR'), name='contribution_decision_consistency'),
        ),
    ]
