# Generated by Django 5.0 on 2025-12-30 07:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=1)),
                ('entry_type', models.CharField(choices=[('award', 'Award'), ('reversal', 'Reversal'), ('adjustment', 'Adjustment')], default='award', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_ledger', to='contributions.contribution')),
            ],
            options={
                'verbose_name': 'Credit Ledger Entry',
                'verbose_name_plural': 'Credit Ledger Entries',
                'db_table': 'credit_ledger_entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
