# Generated by Django 5.0 on 2025-12-30 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credits', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditledgerentry',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditledgerentry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_ledger', to='projects.project'),
        ),
        migrations.AddField(
            model_name='creditledgerentry',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='creditledgerentry',
            index=models.Index(fields=['to_user', '-created_at'], name='ledger_to_user_idx'),
        ),
        migrations.AddIndex(
            model_name='creditledgerentry',
            index=models.Index(fields=['contribution'], name='ledger_contribution_idx'),
        ),
        migrations.AddIndex(
            model_name='creditledgerentry',
            index=models.Index(fields=['created_by_user'], name='ledger_created_by_idx'),
        ),
        migrations.AddConstraint(
            model_name='creditledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'award')), fields=('project', 'to_user'), name='unique_award_per_project_user'),
        ),
    ]
